### ISSUE TITLE
Vega56显卡无法运行

### ISSUE THREAD

**Issue by Babynini** [k7212519/stable-diffusion-webui-AMD-onekey-deploy#1]
显卡vega56，安装了Ubuntu 20.04.6（amd 驱动要求Ubuntu 20.04.5但我没找到链接）
显卡名称显示vega10不知道驱动是否安装成功。
用2.0的脚本最后选择显卡那里选择的是rx5000
打开脚本后第一次会出现如下提示：Page not present or supervisor privilege
第二次会卡在diffusionwapper has 859.52M params.
请问具体是哪步可能出问题？
![DSC_1180](https://user-images.githubusercontent.com/25690791/228105601-aaad6af8-82ad-47a6-ad2a-b333ebe214f3.JPG)
![DSC_1181](https://user-images.githubusercontent.com/25690791/228105607-528112f7-fcc9-441c-81fd-b294ec07ffe6.JPG)

**Comment by k7212519** [comment]
我不确定你这个显卡是否兼容。系统版本Ubuntu 20.04.6应该没问题，是兼容的。请在终端运行 rocm-smi 命令查看是否出现显卡占用，如果没有，请安装官网Ubuntu20.04.5显卡驱动：
sudo apt install xxxxxxx.deb
完成后：
sudo amdgpu-install --usecase=rocm,hip,graphics --no-dkms
完成后运行：
sudo usermod -a -G render $LOGNAME
sudo usermod -a -G video $LOGNAME
完成后重启电脑。
最终输入rocm-smi出现显卡占用信息，再开始使用脚本文件。
如果不行，请等待适配rx500系列，然后参考其进行安装。

**Comment by k7212519** [comment]
也有可能是HBM显存和普通的不一样的问题

**Comment by k7212519** [comment]
使用下面文字替换/dockerx/sh/sd.sh中的原有命令，在最后：
docker exec -it stable-diffusion bash -c "cd /dockerx/stable-diffusion-webui && source venv/bin/activate && REQS_FILE='requirements.txt' PYTORCH_ROCM_ARCH=gfx906 HCC_AMDGPU_TARGET=gfx906 python launch.py" 
替换完成后保存，然后直接重启软件。请勿再次运行setup_sd.sh，不然sd.sh会被还原。
如果成功请及时反馈便于并入项目

**Comment by Babynini** [comment]
这个方法可以成功跑图，现在有个新的问题，我的GPU好像只有8g显存在工作，我的显卡有16g，导致跑稍微大点的图会爆显存。但是16g好像一般不用加启动参数。不知道这算不算问题。
![IMG_20230328_233056870.jpg](https://user-images.githubusercontent.com/25690791/228291305-70e07737-57a9-4a62-9209-7dd04d8af464.jpg)

**Comment by Babynini** [comment]
看上去那个gtt用了我一半的显存，有啥办法调整么？

**Comment by k7212519** [comment]
可否提供报显存错误的信息配图。在跑图片时，尺寸尽量不要超过`1024x1024`，实测大了模型支持得也不好。然后尺寸尽量填写`256`的倍数，比如`1024x1024`，而不要写`1000x1000`，这样不容易出错。如果实在不行，可在`sd.sh`添加启动参数：
```shell
--opt-sub-quad-attention
``` 
或者
```shell
--medvram
``` 
但是`--medvram`可能会影响跑图速度，请自行测试。

**Comment by k7212519** [comment]
另外，作为Vega56显卡，请尝试将sd.sh文件的：
```shell
PYTORCH_ROCM_ARCH=gfx906 HCC_AMDGPU_TARGET=gfx906
``` 
中的两个`gfx906`替换成`gfx900`  
重新测试兼容性，如有更好的效果，请即使反馈给我进行更新。

**Comment by Babynini** [comment]
反馈一下目前的测试结果，
vega56的gttsize暂时无法更改，vega显卡的显存暂时只能用8G
--opt-sub-quad-attention 参数可以显著改善显存的利用率，目前测试跑一个小时图都没有爆显存
--medvram参数目前测试下来没有必要添加
修改sd.sh参数gfx906修改为gfx900 可以跑图但未发现有显著区别
