### ISSUE TITLE
b站 7900xtx来的，问题如下

### ISSUE THREAD

**Issue by PennyFranklin** [k7212519/stable-diffusion-webui-AMD-onekey-deploy#2]
![截图 2023-03-28 17-30-37](https://user-images.githubusercontent.com/104998459/228194635-5de2238a-d6a4-4977-857c-9b509c72d5e1.png)

**Comment by k7212519** [comment]
7900xt暂时未适配，后续支持后第一时间集成

**Comment by PennyFranklin** [comment]
好的好的👌🏻

**Comment by littlewu2508** [comment]
如果想折腾一下可以看看 https://github.com/RadeonOpenCompute/ROCm/issues/1880#issuecomment-1428171582, 里面提供了我几个月前对着 ROCm 各个库当时的 developing branch 为 7900XTX 编译的带 [pytorch 和 torchvision 的 docker](https://hub.docker.com/r/littlewu2508/clang-16_rc2-pytorch-1.12-rocm-9999-5.5-gfx1100)，理论上是支持 7900XTX 的。经过网友测试，一些矩阵运算，以及简单的 pytorch 命令似乎是正常的，但有可能出现显存访问问题（大概需要 cutting edge 的 Linux 内核提供足够新的驱动吧）

**Comment by PennyFranklin** [comment]
好的，我去试试
